# -*- coding: utf-8 -*-
"""4A_ELBO_feature_extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VUdOuZTs2PG5ISHs5Wu5Bnj0ZJvjWsH8

# **FEATURE EXTRACTION NI ELBO**

**STEP 1: LOAD MO YUNG IMAGE NA GUSTO MO**
"""

!pip uninstall opencv-python -y

!pip install opencv-contrib-python

# import muna to
import cv2

# Tapos Load mo na yung images
pic1 = cv2.imread('ryushade.jpg', cv2.IMREAD_GRAYSCALE)
pic2 = cv2.imread('ryuwhiteshade.jpg', cv2.IMREAD_GRAYSCALE)

"""**Step 2: Extract ng Keypoints and Descriptors gamit ang SIFT, SURF, and ORB**"""

# SIFT
sift = cv2.SIFT_create()
keypnts_sift_1, descript_sift_1 = sift.detectAndCompute(pic1, None)
keypnts_sift_2, descript_sift_2 = sift.detectAndCompute(pic2, None)

# AKAZE
akaze = cv2.AKAZE_create()
keypnts_akaze_1, descript_akaze_1 = akaze.detectAndCompute(pic1, None)
keypnts_akaze_2, descript_akaze_2 = akaze.detectAndCompute(pic2, None)

# ORB
orb = cv2.ORB_create()
keypnts_orb_1, descript_orb_1 = orb.detectAndCompute(pic1, None)
keypnts_orb_2, descript_orb_2 = orb.detectAndCompute(pic2, None)

"""**Submission na po**"""

# Display lang kung need
img_sift = cv2.drawKeypoints(pic1, keypnts_sift_1, None, flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
img_akaze = cv2.drawKeypoints(pic1, keypnts_akaze_1, None, flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
img_orb = cv2.drawKeypoints(pic1, keypnts_orb_1, None, flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

# Save the keypoints images
cv2.imwrite('sift_keypoints.jpg', img_sift)
cv2.imwrite('akaze_keypoints.jpg', img_akaze)
cv2.imwrite('orb_keypoints.jpg', img_orb)